modeling:


training:
  # champion time windows written by the script
  history_months: 9
  pred_months: 6
  test_size: 0.20
  early_stopping_rounds: 20
  eval_metric: rmse
  cutoff_date: "2021-12-31"   # (keep or edit as needed)

composite_weights:
  # marketing can tweak these without touching code
  rmse: 0.5
  r2:   0.5

scoring:
  percentile_bins: [0, 0.01, 0.05, 0.10, 0.20, 1.0]
  segment_labels: ["Top 1%", "Top 5%", "Top 10%", "Top 20%", "Others"]

clustering:
  n_clusters: 5
  random_state: 42
  clustering_algorithm: kmeans

monitoring:
  drift_threshold_rmse: 0.20   # retrain if RMSE increases by 20%
  drift_threshold_r2: 0.15      # retrain if R² drops by 15%

general:
  timestamp_format: "%Y%m%d_%H%M%S"
